repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
      - id: ruff
        name: Run ruff on tests/
        args: [--exit-non-zero-on-fix]
        files: ^tests/

  - repo: https://github.com/sphinx-contrib/sphinx-lint
    rev: v1.0.0
    hooks:
      - id: sphinx-lint
        name: Run sphinx-lint on docs/
        args: [--enable=default-role]
        files: ^docs/

  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v19.1.1
    hooks:
      - id: clang-format
        name: Run clang-format on *.c|h
        files: \.(c|h)$
        exclude: ^pythoncapi_compat\.h$
