name: basic
on: [push, pull_request]
jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9, pypy3.9, '3.10', 'pypy3.10', 3.11, 3.12, 3.13]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true
      - run: sudo apt-get update
      - run: sudo apt-get install libgmp-dev
      - run: pip install --upgrade pip
      - run: pip --verbose install --editable .[tests,sphinx,python-sphinx]
      - run: pytest
      - run: sphinx-build --color -W --keep-going -b html docs build/sphinx/html
      - run: sphinx-build --color -W --keep-going -b latex docs build/sphinx/latex
      - run: make -C build/sphinx/latex all-pdf