name: Build & test docs
on:
  workflow_call:
jobs:
  docs:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - run: sudo apt-get update
      - run: sudo apt-get install libgmp-dev
      - run: pip install --upgrade pip
      - run: pip --verbose install .[docs]
      - run: sphinx-build --color -W --keep-going -b html docs build/sphinx/html
      - uses: actions/upload-artifact@v4
        with:
          name: docs
          path: build/sphinx/html/
