name: Run tests on different OS
on:
  workflow_call:
jobs:
  os:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
#       os: [ubuntu-24.04, ubuntu-24.04-arm, macos-14]
#       shell: [bash]
        include:
          - os: windows-2022
            shell: 'msys2 {0}'
    defaults:
      run:
        shell: ${{ matrix.shell }}
    env:
      PYTEST_ADDOPTS: --verbose
      CFLAGS: -Wall -Wpedantic -Werror -std=c17 -Wconversion
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - uses: msys2/setup-msys2@v2.27.0
        with:
          install: >-
            mingw-w64-ucrt-x86_64-pkg-config
            mingw-w64-ucrt-x86_64-gcc
            autotools
            patch
          msystem: ucrt64
        if: ${{ startsWith(matrix.os, 'windows') }}
      - name: Cache GNU GMP builds
        id: cache-gmp
        uses: actions/cache@v4
        with:
          path: .local
          key: ${{ matrix.os }}-${{ hashFiles('scripts/*') }}
      - run: bash scripts/cibw_before_all.sh
        if: steps.cache-gmp.outputs.cache-hit != 'true'
      - run: pip install --upgrade pip
      - run: pip --verbose install .[tests] -Csetup-args=-Dbuildtype=debug
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/.local/lib/pkgconfig
      - run: pytest --hypothesis-profile=default
        env:
          LD_LIBRARY_PATH: ${{ github.workspace }}/.local/lib
