name: Publish on PyPI
on: push
jobs:
  build:
    name: Build distribution
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.13
    - run: pip install build
    - run: python -m build -s
    - uses: actions/upload-artifact@v4
      with:
        name: python-gmp
        path: dist/
  publish-to-pypi:
    name: Publish distribution to PyPI
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - build
    runs-on: ubuntu-22.04
    environment:
      name: pypi
      url: https://pypi.org/p/python-gmp
    permissions:
      id-token: write
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: python-gmp
        path: dist/
    - uses: pypa/gh-action-pypi-publish@release/v1
